### ISSUE TITLE
还能用不

### ISSUE THREAD

**Issue by ghost** [lmgy/NetKeeperDialer#2]
CQUPT还能用不

**Comment by lmgy** [comment]
可以用

**Comment by JianfeiYu** [comment]
我固定TPlink的ip地址（172.24.52.188）yf楼后，然后在NetKeeperDialer随机设置了一个创翼密码，路由器ip地址192.168.1.1以及路由器的登录密码之后，打开netkeeper，账号密码为空，运行NetKeeperDialer，假死状态，等了估计有一分钟，netkeeper并没有获取到密码和账号

**Comment by lmgy** [comment]
首先需要保证你使用的netkeeper的版本是4.7.9.589版本，下载地址https://github.com/lmgy/NetKeeperDialer/blob/master/windows589.rar  最新版本会用不了。这里给你说一下使用步骤。一、打开NetKeeperDialer，在设置里面输入正确的路由器ip和宽带密码。二、安装4.7.9.589版本的netkeeper，然后打开netkeeper，输入你的宽带账号和密码，先不要点登录按钮。三、点NetKeeperDialer的开始截取按钮，然后再点netkeeper的登录按钮。这样才能正确地获取到真实宽带账号。

**Comment by JianfeiYu** [comment]
我用的netkeeper就是你说那个版本，路由器ip是192.168.0.1吗，还是固定ip，提示路由器连接失败

**Comment by JianfeiYu** [comment]
已经提示截取到正确账号，但是出现“连接路由器失败，请检查密码后重试”，我密码正确的，我用chrome输入192.168.0.1 然后输入密码能登陆正常路由器，路由器也是tl-wr842n，我尝试了固定路由器ip地址位172.24.52.188和自动获取也不行，dialer中的ip地址应该是多少

**Comment by lmgy** [comment]
dialer中ip地址是类似192.168.1.1这样的ip地址，具体的需要看你路由器的地址。出现“连接路由器失败”就是说明路由器ip地址错了，无法把截取到的账号发送给路由器，你在使用的时候，保证电脑是wifi或者是网线连着路由器的，而不是直接连着寝室网口

**Comment by JianfeiYu** [comment]
[https://i.loli.net/2019/04/07/5ca9d54f38156.png](url)
路由器的内网IP地址如上，我电脑是直接通过网线连接路由器的，dialer的ip地址配置的192.168.1.1
电脑能直接ping通192.168.1.1，密码也确定是没有错，依旧提示“连接路由器失败。请检查密码后重试”

**Comment by lmgy** [comment]
这个是我路由器的设置，你看一下
![QQ截图20190407201403.jpg](https://i.loli.net/2019/04/07/5ca9e9f385c9f.jpg)
![QQ截图20190407201418.jpg](https://i.loli.net/2019/04/07/5ca9e9f386435.jpg)
